name: Hello World

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: "context"
        env:
          COMMIT_ID: ${{ SECRET.HOST }}
        run: echo "Commit id => $COMMIT_ID"
