name: Hello World

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: "executing remote ssh commands using key"
        with: 
          host: ${{ secrets.HOST }}
        run: echo "Commit id => $host"
